### ISSUE TITLE
betterbib Python API

### ISSUE THREAD

**Issue by adamheins** [nschloe/betterbib#118]
I was thinking that it may be worth considering a unified betterbib API, such that betterbib functionality could be added programmatically to other projects (rather than as a separate CLI tool). For example, something along the lines of:
```python
import betterbib

# Programmatic equivalent of the betterbib tool.
bibtex = betterbib.sync(infile, **kwargs)
bibtex = betterbib.journal_abbrev(bibtex, **kwargs)
bibtex = betterbib.format(bibtex, **kwargs)
```

**Comment by nschloe** [comment]
Fixed now. Check out https://github.com/nschloe/betterbib/blob/master/betterbib/cli/full.py#L31 on how to use it.
