### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 121: ordinal not in range(128)

### ISSUE THREAD

**Issue by Et9797** [nschloe/betterbib#124]
Hi I am using your application for journal abbreviation. I've come across this error that I can't seem to fix for this particular citation.
```
100%|####################################################################################| 1/1 [00:05<00:00,  5.09s/it]

Total number of entries: 1
Found: 1
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\py27_32bit\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\user\anaconda3\envs\py27_32bit\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\user\Anaconda3\envs\py27_32bit\Scripts\betterbib.exe\__main__.py", line 9, in <module>
  File "c:\users\user\anaconda3\envs\py27_32bit\lib\site-packages\betterbib\cli\full.py", line 35, in main
    tools.write(d, args.outfile, args.delimeter_type, tab_indent=args.tab_indent)
  File "c:\users\user\anaconda3\envs\py27_32bit\lib\site-packages\betterbib\tools.py", line 374, in write
    file_handle.write("\n\n".join(segments) + "\n")
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 121: ordinal not in range(128)
```

The BibTex citation in question:
```
@article{meyfroidt2009machine,
	title={Machine learning techniques to examine large patient databases},
	author={Meyfroidt, Geert and Guiza, Fabian and Ramon, Jan and Bruynooghe, Maurice},
	journal={Best Practice \& Research Clinical Anaesthesiology},
	volume={23},
	number={1},
	pages={127--143},
	year={2009},
	publisher={Elsevier}
}
```

Would you be so kind to help me with this? I find it weird this error because for example this citation works perfectly:
```
@article{jiang2017artificial,
  title={Artificial intelligence in healthcare: past, present and future},
  author={Jiang, Fei and Jiang, Yong and Zhi, Hui and Dong, Yi and Li, Hao and Ma, Sufeng and Wang, Yilong and Dong, Qiang and Shen, Haipeng and Wang, Yongjun},
  journal={Stroke and vascular neurology},
  volume={2},
  number={4},
  pages={230--243},
  year={2017},
  publisher={BMJ Specialist Journals}
}
```
I am using python 2.7.15 virtual env with anaconda3.

**Comment by Et9797** [comment]
I tried with other versions of python (3.5 and 3.6) and I keep getting this message

 File "c:\users\user\anaconda3\envs\py36_32bit\lib\site-packages\betterbib\tools.py", line 57, in pybtex_to_dict
    for field, value in entry.fields.iteritems():
AttributeError: 'OrderedCaseInsensitiveDict' object has no attribute 'iteritems'

**Comment by nschloe** [comment]
I cannot reproduce the error. In any case I'd recommend staying away from Python 2.

I believe you're using an outdated version of betterbib. Run
```
betterbib -v
```
to check.

**Comment by Et9797** [comment]
betterbib 3.4.0, Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018,
18:00:36) [MSC v.1915 32 bit (Intel)]. Still getting the above error with this version of Python. Installed betterbib with pip install -U betterbib in Anaconda Python 3.6.8 venv 32 bit (force command),because 64 bit python gives a Pyenchant error. Going to try on my laptop with fresh installation of Python now

**Comment by Et9797** [comment]
Same error AttributeError: 'OrderedCaseInsensitiveDict' object has no attribute 'iteritems' on freshly installed 3.6.8 python 32 bit (no Anaconda)

**Comment by Et9797** [comment]
Seems to be working now in the command prompt. However, it did not abbreviate the journal for Meyfroidt's article unfortunately, and is giving this error in Texstudio now:

>Package inputenc Error: Invalid UTF-8 byte 252. Meyfroidt G, G�
Overfull \hbox (16.78363pt too wide) in paragraph
Underfull \hbox (badness 10000) in paragraph
Underfull \hbox (badness 10000) in paragraph
Underfull \hbox (badness 10000) in paragraph
Underfull \hbox (badness 10000) in paragraph
Underfull \hbox (badness 10000) in paragraph
Underfull \hbox (badness 10000) in paragraph

jiang2017artificial journal was correctly abbreviated like it was in python 2.7 version and isn't showing any problems in Texstudio from the looks of it

**Comment by nschloe** [comment]
> However, it did not abbreviate the journal for Meyfroidt's article unfortunately,

That's because, in the list, the journal is called
```
Best Practice and Research. Clinical Anaesthesiology
```
and not
```
Best Practice & Research. Clinical Anaesthesiology
```
It doesn't find the abbreviation then. I'll fix that.

> and is giving this error in Texstudio now:
> Package inputenc Error: Invalid UTF-8 byte 252. Meyfroidt G, G�

If you're using oldschool bibtex, you'll have to manually convert the umlauts first. My recommendation would be to use biblatex.

**Comment by Et9797** [comment]
Thanks, you're awesome.
