### ISSUE TITLE
Betterbib adds extra space in chemformula 

### ISSUE THREAD

**Issue by nujabse** [nschloe/betterbib#140]
I use [chemformula](https://ctan.org/pkg/chemformula?lang=en) package to handle subscripts and superscripts in chemicals that appear in the article title, like `\ch{H2O2}` . But when I ran `betterbib-journal-abbrev` command on my bib file, betterbib automaticallly adds an extra space between the command "\ch" and the chemical text "{H2O2}" and became "\ch {H2O2}".  The extra space would then make chemformula package unable to work.
Here is the file after running betterbib:
```
@article{lu19_self_cross_mxene_ti3c2_membr,
 author = {Lu, Zong and Wei, Yanying and Deng, Junjie and Ding, Li and Li, Zhong-Kun and Wang, Haihui},
 title = {Self-Crosslinked {MXene} \ch {Ti3C2T\_{x}} Membranes With Good Antiswelling Property for Monovalent Metal Ion Exclusion},
 journal = {ACS Nano},
 volume = {13},
 number = {9},
 pages = {10535-10544},
 year = {2019},
 doi = {10.1021/acsnano.9b04612},
 url = {https://doi.org/10.1021/acsnano.9b04612},
 date_added = {Wed Mar 4 00:35:53 2020},
}
```
While the original bib entry looks like this:
```
@article{lu19_self_cross_mxene_ti3c2_membr,
  author =       {Zong Lu and Yanying Wei and Junjie Deng and Li Ding and
                  Zhong-Kun Li and Haihui Wang},
  title =        {Self-Crosslinked {MXene} \ch{Ti3C2T_{x}} Membranes With Good
                  Antiswelling Property for Monovalent Metal Ion Exclusion},
  journal =      {ACS Nano},
  volume =       13,
  number =       9,
  pages =        {10535-10544},
  year =         2019,
  doi =          {10.1021/acsnano.9b04612},
  url =          {https://doi.org/10.1021/acsnano.9b04612},
  DATE_ADDED =   {Wed Mar 4 00:35:53 2020},
}
```
Is there any option to stop adding spaces bewteen \ch and {}, or just skip changing the title field?

**Comment by nschloe** [comment]
This is an issue with a dependency: https://github.com/mcmtroffaes/latexcodec/issues/80.

**Comment by nschloe** [comment]
Okay, so as explained in the linked issue in latexcodec, the added space is not a problem. LaTeX renders `\ch {Ti3C2T\_{x}}` just as `\ch{Ti3C2T\_{x}}`. If this doesn't work for you, feel free to reopen.

**Comment by nujabse** [comment]
Thanks for the reply! The chemical formula renders just fine!

**Comment by nschloe** [comment]
I don't understand the original comment then

> The extra space would then make chemformula package unable to work.

but fair enough.
