### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by mayrmt** [nschloe/betterbib#145]
I have cloned the repository and have added some more journal abbreviations to `betterbib/data/journals.json`. Before pushing, I'd like to test them. 

Are there any contributing guidelines? In particular, I'm looking for instructions to test modification locally.

**Comment by nschloe** [comment]
Those files are generated from JabRef, see https://github.com/nschloe/betterbib/blob/master/betterbib/data/. You might want to direct the PR to JabRef.

**Comment by mayrmt** [comment]
@nschloe Just as quick follow-up info: I put in a PR to the JabRef repository. Not merged yet, but in the works... Looks like JabRef developers maintain journal lists in several places. I was told, that the 'master' list lives in this repo: https://github.com/JabRef/abbrv.jabref.org
