### ISSUE TITLE
\emph is not preserved

### ISSUE THREAD

**Issue by keithbriggs** [nschloe/betterbib#160]
This

title={A far-travelled word: Old Norse \emph{skei{\dh}}\ `racecourse, running track' in early literature and place-names},

is turned into

title = {A far-travelled word: {Old} {Norse} skei\dh\ \`racecourse, running track` in early literature and place-names},

**Comment by nschloe** [comment]
That's what crossref provides. https://api.crossref.org/v1/works/10.1515/9783110548136-028

**Comment by keithbriggs** [comment]
Then crossref is not useful if you can't trust it.
