### ISSUE TITLE
macron is lost

### ISSUE THREAD

**Issue by keithbriggs** [nschloe/betterbib#161]
This
```
booktitle={Die Faszination des Verborgenen und seine Entschl\\"usselung: \emph{R\\=a{\dh}i s\\=aR kunni}},
```
is turned into
```
booktitle = {Die Faszination des Verborgenen und seine Entschl\\"usselung -- R\\=a\dj i sa?` kunni},
```
The first \\=a is preserved, but not the second.  \emph is also lost.  Also, ":" is turned into "--", which I didn't ask for.

**Comment by nschloe** [comment]
That's what crossref provides. https://api.crossref.org/v1/works/10.1515/9783110548136-028

**Comment by keithbriggs** [comment]
Then crossref is not useful if you can't trust it.

**Comment by nschloe** [comment]
You can adapt the data source with `-s`.

**Comment by keithbriggs** [comment]
But does crossref have a way to fix wrong data?   I just checked several of my articles and every one of them had something wrong.


________________________________

**Comment by nschloe** [comment]
> But does crossref have a way to fix wrong data?

As far as I know, the publishers provide data to crossref. They do little to no sanitation. You can of course write crossref about the wrong entries.
