### ISSUE TITLE
Feature request: flag retracted papers

### ISSUE THREAD

**Issue by martisak** [nschloe/betterbib#169]
In [Data Sceptic: Retraction Watch](https://podcasts.apple.com/uy/podcast/retraction-watch/id890348705?i=1000493667147) Ivan Oransky from [Retraction Watch](https://retractionwatch.com/) highlights the problem that many retracted papers are still cited. He also highlights the [integration with Zotero](https://www.zotero.org/blog/retracted-item-notifications/).

However, I like `betterbib`, so I would love to get a warning if a paper in my BibTeX is retracted. 

I don't think an API exists, so this is not trivial, see more information [here](https://retractionwatch.com/retraction-watch-database-user-guide/).

**Comment by nschloe** [comment]
Good idea. Unfortunately, Retraction Watch is a commercial service and cannot be used by betterbib.
