### ISSUE TITLE
KeyError: u'04' with month="04" in bibtex file

### ISSUE THREAD

**Issue by pierroweb** [nschloe/betterbib#17]
Hi!

Thanks for writing this tool, it is very appealing. I just got the following error, using the command

    betterbib test.bib out-test.bib --sources {mref,crossref

with a fresh install with pip install betterbib.

The bibtex file has a single entry

    @article{lockhart2014significance,
    author = "Lockhart, Richard and Taylor, Jonathan and Tibshirani, Ryan J. and Tibshirani, Robert",
    doi = "10.1214/13-AOS1175",
    fjournal = "The Annals of Statistics",
    journal = "Ann. Statist.",
    number = "2",
    month = "04",
    pages = "413--468",
    publisher = "The Institute of Mathematical Statistics",
    title = "A significance test for the lasso",
    url = "http://dx.doi.org/10.1214/13-AOS1175",
    volume = "42",
    year = "2014"
    }

The traceback is the following:

    Traceback (most recent call last):
      File "/usr/local/bin/betterbib", line 128, in <module>
        _main()
      File "/usr/local/bin/betterbib", line 79, in _main
        a = pybtex_to_bibtex_string(entry, bib_id)
      File "/usr/local/lib/python2.7/dist-packages/betterbib/bibtex.py", line 65, in pybtex_to_bibtex_string
        content.append('%s = %s' % (field, _index_to_month[value]))
    KeyError: u'04'

If I remove the month line

    month = "04",

from the bibtex file, then it works. I hope this is enough to reproduce the bug, let me know if you need more information.

**Comment by pierroweb** [comment]
Similarly, the line

     month = {Nov},

in the bibtex entry raises the traceback

     Traceback (most recent call last):
       File "/usr/local/bin/betterbib", line 128, in <module>
         _main()
       File "/usr/local/bin/betterbib", line 79, in _main
         a = pybtex_to_bibtex_string(entry, bib_id)
       File "/usr/local/lib/python2.7/dist-packages/betterbib/bibtex.py", line 65, in pybtex_to_bibtex_string
         content.append('%s = %s' % (field, _index_to_month[value]))
     KeyError: u'Nov

**Comment by nschloe** [comment]
Thanks for the report! The issues are fixed now, a new version (1.1.2) is released.
