### ISSUE TITLE
error on repeated bib entries

### ISSUE THREAD

**Issue by krober10nd** [nschloe/betterbib#175]
* If a bib entry is repeated in a bib file, the program errors. It would be super cool if it had an option to delete these entries instead.

**Comment by nschloe** [comment]
What do you mean by "entry"? A repeated key?

**Comment by krober10nd** [comment]
A repeated entry in my parlance is this a bib file with the same citation repeated more than once: 

```
@incollection{cgal:hs-chdt3-20b,
 author = {Hert, Susan and Seel, Michael},
 title = {Convex Hulls},
 publisher = {WORLD SCIENTIFIC},
 edition = {{5.1.1}},
 booktitle = {Lectures on Convex Sets},
 url = {https://doi.org/10.1142/9789811202124_0004},
 year = {2020},
 doi = {10.1142/9789811202124_0004},
 pages = {123-147},
 source = {Crossref},
 isbn = {9789811202117, 9789811202124},
 month = jan,
}

@incollection{cgal:hs-chdt3-20b,
 author = {Hert, Susan and Seel, Michael},
 title = {Convex Hulls},
 publisher = {WORLD SCIENTIFIC},
 edition = {{5.1.1}},
 booktitle = {Lectures on Convex Sets},
 url = {https://doi.org/10.1142/9789811202124_0004},
 year = {2020},
 doi = {10.1142/9789811202124_0004},
 pages = {123-147},
 source = {Crossref},
 isbn = {9789811202117, 9789811202124},
 month = jan,
}
```

**Comment by nschloe** [comment]
When trying to parse this one, I'm getting
```
pybtex.database.BibliographyDataError: repeated bibliograhpy entry: cgal:hs-chdt3-20b
```
Since this happens in pybtex, there isn't much I can do about it in betterbib. I could write my own bibtex parser, but no. :smile: 

It's a good thing betterbib errors out with a clear error message. At least this enables the user to do something about it.

**Comment by krober10nd** [comment]
True, it's really just a mistake on the user anyway. I had a bib that I just used this on and it discovered several duplicates anyway. I just systematically deleted them and called it a day.
