### ISSUE TITLE
Issues with output

### ISSUE THREAD

**Issue by jiiihpeeh** [nschloe/betterbib#176]
From the README
```
@article{krylov,
 author = {Gaul, André and Gutknecht, Martin H. and Liesen, Jörg and Nabben, Reinhard},
 title = {A Framework for Deflated and Augmented {Krylov} Subspace Methods},
 doi = {10.1137/110820713},
 number = {2},
 pages = {495-518},
 source = {Crossref},
 url = {https://doi.org/10.1137/110820713},
 volume = {34},
 journal = {SIAM J. Matrix Anal. \& Appl.},
 publisher = {Society for Industrial \& Applied Mathematics (SIAM)},
 issn = {0895-4798, 1095-7162},
 year = {2013},
 month = jan,
}
```
 month = jan, <--see this. Many Python BibTeX parsers fail due to this.
I think it  should output
 month = {jan},
I also have occasional Unicode issues with it.
Anyway, I used your codebase and I have fixed those issues myself for my own project (but it is quite heavily modified, so...).
SQLite db seems to have issues when I run betterbib in concurrent threads and program exits due to buffer issues... This might be beyond the scope of this project since I suppose it is a parser issue.

**Comment by nschloe** [comment]
> month = jan, <--see this. Many Python BibTeX parsers fail due to this.

Really? I've never seen a single one. The difference between `jan` and `{jan}` is that that `{jan}` is always shown literally as "jan" in the reference, whereas `jan` is the first month of the year and, depending of the language of the document, is "January", "Janvier", "enero" etc.

**Comment by jiiihpeeh** [comment]
Oh, it might be an issue with parser versions or something. When I refeed it to betterbib it gives a parser error. It can also be an issue with mixed use of curly brackets which might confuse them.

**Comment by nschloe** [comment]
> When I refeed it to betterbib it gives a parser error. It can also be an issue with mixed use of curly brackets which might confuse them.

Might well be. Bibtex parsers aren't very "robust". Bisection is your friend when trying to find the offending entry.

**Comment by nschloe** [comment]
Feel free to reopen if you get to the bottom of this.
