### ISSUE TITLE
Conserve `preamble` declarations

### ISSUE THREAD

**Issue by JensHeinrich** [nschloe/betterbib#198]
As `@preamble` declarations are officially supported by `bibtex` they should not be dropped when reformatting the file.

(already on implementing it)

**Comment by JensHeinrich** [comment]
There is now an official property `preamble_list` to get the preamble as list 
[since this commit](https://bitbucket.org/pybtex-devs/pybtex/commits/bc495ada9e01c6bb4a82b91cdc89f7ae838e186c)

**Comment by nschloe** [comment]
Let's add a comment in the PR to replace `_preamble` by `preamble_list`.

**Comment by nschloe** [comment]
Fixed by #199.
