### ISSUE TITLE
Using LaTeX accents

### ISSUE THREAD

**Issue by haji-ali** [nschloe/betterbib#218]
Is there a way to configure betterbib to you latex accents instead of unicode characters?
I prefer using latex accents because it requires fewer packages when using the bib file.

**Comment by nschloe** [comment]
`update` now has `-a` which forces the output to use LaTeX.

**Comment by haji-ali** [comment]
I just got around to trying this feature and I noticed a couple of regressions

* '&' character (at least in journal and publisher names) are not being replaced by `&` instead of the correct `\&` which causes compilation errors.
* en dash and em dash characters are no longer replaced by `--` or `---` but are kept as unicode characters.
* I believe that capital characters in the title used to be surrounded by `{...}` which preserved their state. This is no longer the case.
