### ISSUE TITLE
Incorrect replacement

### ISSUE THREAD

**Issue by jannisborn** [nschloe/betterbib#220]
Thanks for the nice package!

The journal `Bioinformatics` is being replaced with `Method. Biochem. Anal.`
This is incorrect, as per CASSI, `Bioinformatics` does not require an abbreviation: https://cassi.cas.org/publication.jsp?P=eCQtRPJo9AQyz133K_ll3zLPXfcr-WXfzC0f2rDu7jt-hdyj2IrF7DLPXfcr-WXfMs9d9yv5Zd_72xFCYgjEkzLPXfcr-WXfMs9d9yv5Zd8lhk4KUstlF2wOm4mJuHLo

**Comment by nschloe** [comment]
The report belongs [here](https://github.com/JabRef/abbrv.jabref.org). It appears that the file `journal_abbreviations_webofscience.csv` contains the wrong entry.

**Comment by jannisborn** [comment]
Ok let's keep this open until the problem is corrected upstream, see PR [here](https://github.com/JabRef/abbrv.jabref.org/issues/92)

**Comment by jannisborn** [comment]
Ok, the upstream PR has been merged. 
Then, I re-installed `betterbib` and performed the same command again and the issue persists. 

Here's an example for debugging:

```bib
@article{karimi2019deepaffinity,
  title={DeepAffinity: interpretable deep learning of compound--protein affinity through unified recurrent and convolutional neural networks},
  author={Karimi, Mostafa and Wu, Di and Wang, Zhangyang and Shen, Yang},
  journal={Bioinformatics},
  volume={35},
  number={18},
  pages={3329--3338},
  year={2019},
  publisher={Oxford University Press}
}
```

**Comment by jannisborn** [comment]
Just wanted to let you know that the issue still persists... To me, it does not seem that `betterbib` uses the updated reference list from `JabRef`.

**Comment by nschloe** [comment]
It does. Something else must be wrong, perhaps still in JabRef.
