### ISSUE TITLE
Using the correct dash for page ranges

### ISSUE THREAD

**Issue by haji-ali** [nschloe/betterbib#230]
In the last version of betterbib, I noticed that the page range are using `-` or sometimes a unicode character for en-dash (I guess depending on the original CrossRef entry). Can these always be replaced by `--`?

**Comment by nschloe** [comment]
There now is the `-p` option that let's you specify the separator. It defaults to `--` right now, but this might change depending on the backlash. (Some people argue that the BibTeX file is just for storing information, not for styling.)

**Comment by anntzer** [comment]
Unfortunately, betterbib now keeps expanding `-` into `--`, which means that repeatedly updating a bib file (e.g. because you added more entries) progressively turns the things into `----` then `--------` and so on.

**Comment by haji-ali** [comment]
@nschloe, oh I see. I still think that the em and en dashes could be replaced by `--` and `---` when passing `-a` which does not seem to be the case currently (see https://github.com/nschloe/betterbib/issues/218#issuecomment-998717759).

**Comment by nschloe** [comment]
@haji-ali Handled in https://github.com/nschloe/betterbib/pull/239.
