### ISSUE TITLE
Better handle contradictory journal abbreviations from Crossref

### ISSUE THREAD

**Issue by anntzer** [nschloe/betterbib#233]
Thanks for this useful tool!

Journal abbreviations from Crossref can be a bit inconsistent.  For example, the following entries are both from PNAS: https://api.crossref.org/v1/works/10.1073/pnas.1719906115 https://api.crossref.org/v1/works/10.1073/pnas.1215175109 but the first one has a short-container-title of "Proc Natl Acad Sci USA" whereas the second one has "Proceedings of the National Academy of Sciences" which later gets abbreviated by betterbib into "Proc. Natl. Acad. Sci."

Perhaps betterbib could check whether there are cases where two different entries with the same journal name end up with two different abbreviations, and do something (prefer the Crossref abbreviation, or prefer its own autogenerated abbreviation), perhaps togglable, about it?

**Comment by nschloe** [comment]
Fixed in 4.1.2. Thanks for the report!

**Comment by anntzer** [comment]
Thanks for the quick fix!
