### ISSUE TITLE
journals.json is inconsistent as to whether abbreviations are dotted

### ISSUE THREAD

**Issue by anntzer** [nschloe/betterbib#241]
For example, "The journal of chemical physics" maps to "J Chem Phys" whereas "The Journal of Geometric Analysis" is "J. Geom. Anal." -- and autogenerated names also get final dots.  So after `aj`, the rendered bibliography can get the same inconsistency.  My guess is that you should just fix journals.json by checking for each word whether it was an abbreviation of a word in the journal title and, if so, forcefully add a dot there was none.

**Comment by nschloe** [comment]
This should probably be moved to https://github.com/JabRef/abbrv.jabref.org/tree/main/journals where `journals.json` comes from.

**Comment by anntzer** [comment]
Looks like that's already at https://github.com/JabRef/abbrv.jabref.org/issues/79.

**Comment by nschloe** [comment]
Yup, let's focus on this.
