### ISSUE TITLE
Missing dependency: tqdm

### ISSUE THREAD

**Issue by nchopin** [nschloe/betterbib#25]
Hi, 
betterbib seems to depend on package tqdm, but tqdm is not listed as a dependency in setup.py. (This dependency is not mentioned on the web-site either). 

Thus, on Ubuntu:
sudo pip install betterbib 
installs betterbib only, and betterbib fails to run

> ImportError: No module named tqdm

Or course an easy fix is to do first: 
sudo pip install tqdm

Cheers
NC

**Comment by nschloe** [comment]
Thanks! I just released a fixed version.
