### ISSUE TITLE
missing dependency: pybtex

### ISSUE THREAD

**Issue by thorade** [nschloe/betterbib#28]
Running `pip install betterbib` in WinPython 3.4 64bit failed with error pybtex not found.
After running `pip install pybtex` I was able to install betterbib using `pip install betterbib`, so for me pybtex was the only missing dependency.

**Comment by thorade** [comment]
Sorry, I just saw that it is already listed in requirements.txt:
https://github.com/nschloe/betterbib/blob/master/requirements.txt
Still, installation failed, as described above. Not sure why.
Probably a local problem & this issue can be closed.

**Comment by nschloe** [comment]
Hm, weird. As you noticed correctly, the dependency is listed in `requirements.txt` as well as `setup.py`. Let's close this one, but feel free to reopen in case this occurs again.

**Comment by thorade** [comment]
Same problem occured when installing betterbib in WinPython 2.7.9 32bit.
After installing pybtex, installation of betterbib ran smoothly.

**Comment by thorade** [comment]
Installation in WinPython 2.7.10 also fails.
Maybe spaces are not allowed?
`pybtex>=0.19`
instead of
`pybtex >= 0.19`
