### ISSUE TITLE
assert r.ok AssertionError

### ISSUE THREAD

**Issue by thorade** [nschloe/betterbib#39]
The following entry 
```tex
@InBook{BIMEnergie,
  chapter = {18},
  pages = {293--303},
  title = {BIM f\"{u}r die Energiebedarfsermittlung und Geb\"{a}udesimulation},
  publisher = {VDI Buch, Springer Verlag},
  doi = {10.1007/978-3-658-05606-3_18},
  year = {2015},
  author = {van Treeck, Christoph and Wimmer, Reinhard and Maile, Tobias}
}
```

gives me the following error:
```
Reading from: refin.bib
Saving to: refout.bib
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\Scripts\betterbib", line 100, in <module>
    _main()
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\Scripts\betterbib", line 52, in _main
    result = source.find_unique(entry)
  File "C:\Users\mthorade\Documents\Python\WinPython-32bit-3.5.1.2\python-3.5.1\lib\site-packages\betterbib\crossref.py", line 160, in find_unique
    assert r.ok
AssertionError
```
Note: I was already getting the error before the most recent fixes, so it seems to be unrelated to those.

**Comment by thorade** [comment]
Same error for this entry:
```tex
@InCollection{Alessio2009,
  author    = {Alessio, Alessandro and Bemporad, Alberto},
  title     = {A Survey on Explicit Model Predictive Control},
  booktitle = {Nonlinear Model Predictive Control},
  publisher = {Springer Berlin Heidelberg},
  year      = {2009},
  editor    = {Magni, Lalo and Raimondo, DavideMartino and Allg{\"{o}}wer, Frank},
  volume    = {384},
  series    = {Lecture Notes in Control and Information Sciences},
  pages     = {345--369},
  doi       = {10.1007/978-3-642-01094-1_29},
  isbn      = {978-3-642-01093-4},
  language  = {English}
}
```

**Comment by nschloe** [comment]
Network down?

**Comment by thorade** [comment]
On my machine, I can reproduce it as often as I want. And writing issues on github still works, so there is some network :-)

**Comment by nschloe** [comment]
Cannot reproduce; this is typically a network error of sorts. You can debug further by `print`ing `r` and getting the HTTP status code.

**Comment by thorade** [comment]
Hm, just adding `print(r)` to line 160 of creossref.py does not print anything for me.
Strange thing is, if I delete e.g. the DOI from the entries, everything works, and the output has the missing DOI added.
But with the entries as shown above, I keep getting the AssertionError, at work, at home, and using VPN.

**Comment by nschloe** [comment]
It'd be really interesting to get the HTTP error code. I think it's `r.status_code`. (Check http://docs.python-requests.org/en/master/user/quickstart/).

**Comment by thorade** [comment]
So the error message is telling me exactly what file and line it is coming from, but when I add `print("test")` in the line above, it does not get printed!? But the line number of the error message changes, so it is using that file.

**Comment by thorade** [comment]
OK, it is just printing to an unexpected place. I get stauts code 500

**Comment by nschloe** [comment]
HTTP 200 means okay, 500 is an internal server error over at crossref. Nothing we can do about that.
