### ISSUE TITLE
betterbib fails when trying to match paper (without DOI?)

### ISSUE THREAD

**Issue by fabbra** [nschloe/betterbib#61]
Hi,

I am trying to use _betterbib_ to polish the bibliography of my PhD thesis, in particular to have nicely abbreviated journal names.
However, currently I'm running into issues that it fails on the following bibtex entry:
```
@article{vossoughi_compressibility_1980,
	title = {Compressibility of the myocardial tissue},
	volume = {1980},
	journal = {Adv Bioeng},
	author = {Vossoughi, Jafar and Vaishnav, Ramesh N. and Patel, Dali J.},
	year = {1980},
	keywords = {\_tablet},
	pages = {45--48}
}
```

It's a relatively old paper lacking a DOI. 
Is it possible that is the issue?

Thanks a lot in advance for your help,
Fabian

PS: Here we go with the error messages:
> Reading from: xyz.bib
> Saving to: xyz_fixed.bib
> 
>   5%|███▊                                                                             | 21/446 [00:48<16:12,  2.29s/it]Traceback (most recent call last):
>   File "C:\bin\Anaconda3\lib\site-packages\pybtex\database\__init__.py", line 356, in __getitem__
>     return super(FieldDict, self).__getitem__(key)
>   File "C:\bin\Anaconda3\lib\site-packages\pybtex\utils.py", line 154, in __getitem__
>     return self._dict[key.lower()]
> KeyError: 'url'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\bin\Anaconda3\Scripts\betterbib", line 125, in <module>
>     _main()
>   File "C:\bin\Anaconda3\Scripts\betterbib", line 63, in _main
>     d = betterbib.bibtex.sanitize_doi_url(result if result else entry)
>   File "C:\bin\Anaconda3\lib\site-packages\betterbib\bibtex.py", line 190, in sanitize_doi_url
>     m = re.match('https?://(?:dx\\.)?doi\\.org/(.*)', entry.fields['url'])
>   File "C:\bin\Anaconda3\lib\site-packages\pybtex\database\__init__.py", line 364, in __getitem__
>     raise KeyError(key)
> KeyError: 'url'

**Comment by fabbra** [comment]
Here we go with another entry causing the same error:

```
@book{riffenburgh_statistics_2012,
	title = {Statistics in {Medicine}},
	isbn = {978-0-12-384865-9}
	language = {en},
	publisher = {Academic Press},
	author = {Riffenburgh, Robert H.},
	month = aug,
	year = {2012},
	note = {Google-Books-ID: Pd4KCgJeXeEC},
	keywords = {Mathematics / Probability \& Statistics / General, Medical / Physiology, Science / Life Sciences / Human Anatomy \& Physiology}
}
```

**Comment by nschloe** [comment]
Fixed now.
