### ISSUE TITLE
betterbib doesn't work on Windows

### ISSUE THREAD

**Issue by andalou** [nschloe/betterbib#66]
I'm using python3 from https://www.python.org on Windows 7. I've installed betterbib with `pip3 install -U betterbib`. Then, when I do `betterbib -v` I get:

```
Traceback (most recent call last):
  File "C:\Python36-32\Scripts\betterbib.py", line 14, in <module>
    import betterbib
  File "C:\Python36-32\Scripts\betterbib.py", line 15, in <module>
    from betterbib import pybtex_to_bibtex_string
ImportError: cannot import name 'pybtex_to_bibtex_string'
```

I cannot use betterbib with python3 on Windows. It also doesn't work with python2.

-- 
Cesar

**Comment by nschloe** [comment]
No idea why that should be. The function `pybtex_to_bibtex_string` is contained in `betterbib.tools`.

**Comment by nschloe** [comment]
Any feedback here?

**Comment by nschloe** [comment]
I've found one issue, hopefully this fixes your bug. If not, feel free to reopen.

**Comment by andalou** [comment]
The pip command for installation creates a betterbib file without the .py extension. That doesn't work on Windows. I have to manually add a .py extension to betterbib. Notwithstanding that, when I enter 'betterbib.py -v' I get the following:

----------
Traceback (most recent call last):
  File "C:\Python36-32\Scripts\betterbib.py", line 9, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures
----------

**Comment by nschloe** [comment]
No idea why that should be; `concurrent.futures` is part of Python since 3.2; see https://docs.python.org/3/library/concurrent.futures.html.

**Comment by andalou** [comment]
I think the problem is with your python files not having .py extension.
On Windows you need the .py extension, because Windows ignores the shebang.

**Comment by nschloe** [comment]
The Python documentation seems to differ (https://docs.python.org/3/using/windows.html#shebang-lines):

> For example, if the first line of your script starts with
> ```
> #! /usr/bin/python
> ```
> The default Python will be located and used. As many Python scripts written to work on Unix will already have this line, you should find these scripts can be used by the launcher without modification.

I'm wondering why this doesn't work out of the box here. Perhaps because betterbib is `python3`?
