### ISSUE TITLE
Skipping entries

### ISSUE THREAD

**Issue by stzellerhoff** [nschloe/betterbib#70]
Dear all,

is it possible to skip entries that already contain a doi field?

Thanks in advance!

**Comment by nschloe** [comment]
Why would you want to skip those?

**Comment by stzellerhoff** [comment]
I use betterbib on bibtex file created by grobid and some reference extracted from scientific pdfs already contain doi information. Excluding those would speed up the consolidation process...

**Comment by nschloe** [comment]
Well, betterbib doesn't simply add the DOI, it retrieved all other information from online sources as well. This fixes typos in the article title, wrong publication year and all that.

**Comment by nschloe** [comment]
Closing this for lack of response. Feel free to reopen at any time though!
