### ISSUE TITLE
No-change entries are changed

### ISSUE THREAD

**Issue by rpspringuel** [nschloe/betterbib#79]
Take the following entry (which is typical of an entry created and maintained by BibDesk) as a sample:

```
@book{Johnson:1969,
	Address = {Cambridge},
	Author = {Johnson, Marshall D.},
	Date-Added = {2017-10-25 01:01:41 +0000},
	Date-Modified = {2017-10-31 00:56:37 +0000},
	Publisher = {Cambridge University Press},
	Read = {1},
	Title = {The Purpose of Biblical Genealogies: With Special Reference to the Setting of the Genealogies of Jesus},
	Year = {1969}}
```

This resource has no entry on CrossRef (so far as I can find) and thus there is nothing for betterbib to correct when it encounters this entry.  However, when run through betterbib, it comes out as follows:

```
@book{Johnson:1969,
 Author = {Johnson, Marshall D.},
 Address = {Cambridge},
 Date-Added = {2017-10-25 01:01:41 +0000},
 Date-Modified = {2017-10-31 00:56:37 +0000},
 Publisher = {Cambridge University Press},
 Read = {1},
 Title = {The Purpose of Biblical Genealogies: With Special Reference to the Setting of the Genealogies of Jesus},
 Year = {1969},
}
```

Several things have been changed in this entry, though none are related to the content of the fields: Author field is now first, leading tabs are replaced by spaces, a comma and new line have been added before the closing brace.  As a result of these changes, this entry reads as changed when the input and output file are compared using diff (or similar program).  Since every entry in my database is consistently formatted in the first style, this makes it extremely difficult to check the work that betterbib has done and decide whether it's made good corrections.

I'd like, therefore, for one of two options to be implemented:

1. Entries which are not found in the source (CrossRef in the above case) are reproduced in the outfile exactly as they were in the infile
2. Add the option of a null source (or a "format only" run).  I.e. nothing is actually looked up, but betterbib reformats each entry so that the resulting outfile can be used as the infile for a second run where an entry which is not found in the chosen source won't have any formatting changes that would cause diff to mark it as changed.

Option 1 would be nicer for my workflow, but I suspect that option 2 may be easier to implement under the hood (as it won't require a new method for writing entries to the outfile).

**Comment by nschloe** [comment]
Thanks for the report!

The way betterbib works under the hood is that it parses the file using [pybtex](https://pybtex.org) – and at that point, all formatting information is lost already. So, yeah, to preserve the formatting, I'd have to write my own parser, which is probably outside the scope of betterbib.

I'll implement your second suggestion though and add a small tool for bib file formatting.

**Comment by nschloe** [comment]
Alright, I've made a few changed to make things easier for you and everyone else.

1. `betterbib` is now `betterbib-sync`
2. There's now a new tool `betterbib-format`
3. They read/write from/to standard i/o, so they can be chained together.

What you can do to preserve tabs in the the output is to run
```
betterbib-sync in.bib | betterbib-format -t - out.bib
```

**Comment by rpspringuel** [comment]
The ability to pipe is nice, but since betterbib rearranges the order of the fields in an entry, it isn't as useful from a diff point of view.  True, with the tabs I no longer get whole entries marked as changed, but some parts of each entry are still marked as changed because of the reordered fields.  What I have to do to use diff to check betterbib's work is as follows:

1. `betterbib-format in.bib temp.bib`
2. `betterbib-sync temp.bib out.bib`
3. `diff temp.bib out.bib`

In this way the only changes that are marked are due to the actual data correction step.

Still, the fact that I can now do this is a big improvement.  Thanks.

**Comment by nschloe** [comment]
Alright, fixed that now too. The only thing I cannot influence is the fact that the author name is always separate from the rest; I deliberately put it first all the time. The other entries should remain in order.
