### ISSUE TITLE
Dropped Author field

### ISSUE THREAD

**Issue by rpspringuel** [nschloe/betterbib#83]
Occasionally the author field is being dropped from the source to the original.  Take the following entry as sample:

```
@article{Lincoln_2013,
 year = 2013,
 publisher = {Johns Hopkins University Press},
 volume = {132},
 number = {3},
 pages = {639--658},
 author = {Andrew T. Lincoln},
 title = {Luke and Jesus' Conception: A Case of Double Paternity?},
 journal = {Journal of Biblical Literature}
}
```
This entry is taken from CrossRef (first result when searching on the title), but with the doi and url fields removed.  When run through betterbib I get:
```
@article{Lincoln_2013,
 year = {2013},
 publisher = {JSTOR},
 volume = {132},
 number = {3},
 pages = {639},
 title = {{Luke} and Jesus' Conception: {A} Case of Double Paternity?},
 journal = {Journal of Biblical Literature},
 doi = {10.2307/23487891},
 source = {Crossref},
 url = {http://dx.doi.org/10.2307/23487891},
 issn = {0021-9231},
}
```
As you can see, the author field has been lost.  It also appears that betterbib is grabbing the JSTOR entry rather than original publisher's version.  Maybe that has something to do with it?

**Comment by nschloe** [comment]
Thanks for the detailed report. Fixed now.
