### ISSUE TITLE
Dropped Editor field

### ISSUE THREAD

**Issue by rpspringuel** [nschloe/betterbib#85]
Take the following entry as an example:
```
@incollection{Edwin_2010,
 Editor = {Bergmann, Michael and Murray, Michael J and Rea, Michael C},
 author = {Edwin, Curley},
 doi = {10.1093/acprof:oso/9780199576739.003.0006},
 url = {https://doi.org/10.1093%2Facprof%3Aoso%2F9780199576739.003.0006},
 year = {2010},
 month = nov,
 publisher = {Oxford University Press},
 pages = {58--78},
 title = {The God of Abraham, Isaac, and {Jacob}},
 booktitle = {Divine Evil?},
}
```
The entry is taken from CrossRef, except that I've manually added the Editor field because that information is missing from the CrossRef entry.  When run through betterbib I get back the following:
```
@incollection{Edwin_2010,
 author = {Edwin, Curley},
 doi = {10.1093/acprof:oso/9780199576739.003.0006},
 url = {http://dx.doi.org/10.1093/acprof:oso/9780199576739.003.0006},
 year = {2010},
 month = nov,
 publisher = {Oxford University Press},
 pages = {58-78},
 title = {The God of Abraham, Isaac, and {Jacob}},
 booktitle = {Divine Evil?},
 source = {Crossref},
 isbn = {9780199576739},
}
```
The Editor field has been dropped.  That's consistent with the CrossRef entry, but also inappropriate for this kind of resource (an edited book with chapters by multiple authors) in the citation styles that I use.  That editor field needs to be retained even if CrossRef is missing it for some reason.

**Comment by nschloe** [comment]
Fixed now, thanks for the report!
