### ISSUE TITLE
Version 3.0.3 crashes with TypeError

### ISSUE THREAD

**Issue by Ohjeah** [nschloe/betterbib#87]
I get this traceback:

```
Traceback (most recent call last):
  File "./bin/betterbib", line 214, in <module>
    _main()
  File "./bin/betterbib", line 45, in _main
    _write(od, args.outfile, args.delimeter_type)
  File "./bin/betterbib", line 128, in _write
    dictionary=dictionary
TypeError: pybtex_to_bibtex_string() got an unexpected keyword argument 'bracket_delimeters'
```

I am using

```
$ betterbib -v
betterbib 3.0.3, Python 3.6.2 | packaged by conda-forge | (default, Jul 23
2017, 22:59:30) [GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
```

Version 2.5 works for my bibfile.

**Comment by Ohjeah** [comment]
I guess you changed the cli:

`betterbib in.bib out.bib` does not work anymore, but `betterbib-sync in.bib | betterbib-format -t -b - out.bib` does.

The old worldflow is still on the [Readme](https://github.com/nschloe/betterbib/blob/master/README.md#usage) though.

**Comment by nschloe** [comment]
Thanks for the report; fixed now.

By the way, you could just
```
betterbib-sync in.bib out.bib
```
if you just want to sync your files.

**Comment by Ohjeah** [comment]
How about aliasing betterbib-sync with betterbib for backwards compatibility?

**Comment by nschloe** [comment]
Well, betterbib did more something like what betterbib-sync and betterbib-format did together. I bumped the major version, so technically we're clean here.

I'll think about readding a betterbib exec though.

**Comment by nschloe** [comment]
I've now added a `betterbib` command that replicates approximately what the old `betterbib` did. If you want to tweak it, you'll have to use the `betterbib-*` tools though.
