### ISSUE TITLE
An option to change characters into UTF8

### ISSUE THREAD

**Issue by Edenharder** [nschloe/betterbib#89]
It seems that `betterbib` will automatically change something like `{\'e}` into `é`. It's more safe for me to use `{\'e}`. Is there any option to disable changing characters like `{\'e}` into its UTF8 corresponding `é`?

**Comment by nschloe** [comment]
Unfortunately not. The data retrieved from upstream is in UTF-8, so that's the way it comes out of betterbib-sync. The fix would be to use biblatex/biber. It's superior to bibtex on many levels, one of them being unicode support.

**Comment by Edenharder** [comment]
You are right. But the templates of some journals do not compatible with biblatex. For example, [RevTex4-1](https://ctan.org/pkg/revtex4-1?lang=en) which loads `natbib` by default.

**Comment by Edenharder** [comment]
It seems that the abbreviation of the journal can be done without `sync` other parts of the items, for example, [this python script](https://gist.github.com/peci1/4e67f3d0521ce014fc952bcca664b37d). Is it possible to separate  the functionality "the abbreviation of the journal" from `betterbib-sync`?

**Comment by nschloe** [comment]
> You are right. But the templates of some journals do not compatible with biblatex. For example, RevTex4-1 which loads natbib by default.

Yeah I know. :(

I'd been thinking about implementing a UTF-8 to LaTeX conversion tool, but this is more difficult that one might initially think. Before offering a half-baked version, it's easier for me and more consistent for the user to use what's already out there: biblatex. If your journal doesn't offer it, it's time to put some pressure on their devs to emerge from the cave and use a modern bib-system.

If you only have to deal with a few special characters, perhaps a simple `sed` script will do the trick for you.
