### ISSUE TITLE
UTF-8 errors

### ISSUE THREAD

**Issue by koroki** [nschloe/betterbib#97]
Betterbib has a lots of problems with not acsii characters. In science is really common to find this characters, such as  ° or  Å, in titles or abstracts. When betterbibfind this kind of characters, simply give a generic error, there is not any information about the position or whats the error. 
```
Traceback (most recent call last):
  File ".local/bin/betterbib-sync", line 5, in <module>
    pkg_resources.run_script('betterbib==3.2.0', 'betterbib-sync')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/EGG-INFO/scripts/betterbib-sync", line 130, in <module>
    _main()
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/EGG-INFO/scripts/betterbib-sync", line 44, in _main
    betterbib.write(od, args.outfile, 'braces', tab_indent=False)
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/betterbib/tools.py", line 324, in write
    dictionary=dictionary,
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/betterbib/tools.py", line 193, in pybtex_to_bibtex_string
    value = codecs.encode(value, 'ulatex')
  File ".local/lib/python2.7/site-packages/latexcodec/codec.py", line 800, in encode
    encoder.encode(unicode_, final=True),
  File ".local/lib/python2.7/site-packages/latexcodec/lexer.py", line 483, in encode
    raise ValueError(e)
ValueError: 'latex' codec can't encode character u'\u2009' in position 0: don't know how to translate u'\u2009' into latex
```

Also is common to find names or surnames with special characters, like ñ. I solve it changing the import sys for:
```
import sys
reload(sys)
sys.setdefaultencoding('utf8')`
```
in betterbib-sync

**Comment by nschloe** [comment]
This shouldn't happen indeed. How to you generate the problem exactly? I've never seen it before.

**Comment by koroki** [comment]
I generate it with, for example, this cite: doi:10.1021/ct700301q

I downloaded the citation from the JCTC web site

@article{doi:10.1021/ct700301q,
author = {Hess, Berk and Kutzner, Carsten and van der Spoel, David and Lindahl, Erik},
title = {GROMACS 4:  Algorithms for Highly Efficient, Load-Balanced, and Scalable Molecular Simulation},
journal = {Journal of Chemical Theory and Computation},
volume = {4},
number = {3},
pages = {435-447},
year = {2008},
doi = {10.1021/ct700301q},
    note ={PMID: 26620784},

URL = { 
        http://dx.doi.org/10.1021/ct700301q
    
},
eprint = { 
        http://dx.doi.org/10.1021/ct700301q
    
}
,
    abstract = { Molecular simulation is an extremely useful, but computationally very expensive tool for studies of chemical and biomolecular systems. Here, we present a new implementation of our molecular simulation toolkit GROMACS which now both achieves extremely high performance on single processors from algorithmic optimizations and hand-coded routines and simultaneously scales very well on parallel machines. The code encompasses a minimal-communication domain decomposition algorithm, full dynamic load balancing, a state-of-the-art parallel constraint solver, and efficient virtual site algorithms that allow removal of hydrogen atom degrees of freedom to enable integration time steps up to 5 fs for atomistic simulations also in parallel. To improve the scaling properties of the common particle mesh Ewald electrostatics algorithms, we have in addition used a Multiple-Program, Multiple-Data approach, with separate node domains responsible for direct and reciprocal space interactions. Not only does this combination of algorithms enable extremely long simulations of large systems but also it provides that simulation performance on quite modest numbers of standard cluster nodes. }
}

And in the title there is a ":" that is not acsii. 

It makes an error in batterbib, al most in my betterbib:

Traceback (most recent call last):
  File ".local/bin/betterbib-sync", line 5, in <module>
    pkg_resources.run_script('betterbib==3.2.0', 'betterbib-sync')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/EGG-INFO/scripts/betterbib-sync", line 130, in <module>
    _main()
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/EGG-INFO/scripts/betterbib-sync", line 44, in _main
    betterbib.write(od, args.outfile, 'braces', tab_indent=False)
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/betterbib/tools.py", line 324, in write
    dictionary=dictionary,
  File ".local/lib/python2.7/site-packages/betterbib-3.2.0-py2.7.egg/betterbib/tools.py", line 193, in pybtex_to_bibtex_string
    value = codecs.encode(value, 'ulatex')
  File ".local/lib/python2.7/site-packages/latexcodec/codec.py", line 800, in encode
    encoder.encode(unicode_, final=True),
  File ".local/lib/python2.7/site-packages/latexcodec/lexer.py", line 483, in encode
    raise ValueError(e)
ValueError: 'latex' codec can't encode character u'\u2009' in position 0: don't know how to translate u'\u2009' into latex



I installed bettetbib with pip, in local dir with --prefix=

**Comment by nschloe** [comment]
(Just FYI, you can fence in code blocks with triple backticks in Github. Also, perhaps reread your own post? Spelling errors sometimes give me a hard time.)

I cannot reproduce the error. I tried your example with
```
betterbib in.bib
```
and it correctly generated
```
@article{doi:10.1021/ct700301q,
 author = {Hess, Berk and Kutzner, Carsten and van der Spoel, David and Lindahl, Erik},
 title = {{GROMACS} 4:\textasciitilde\ Algorithms for Highly Efficient, Load-Balanced, and Scalable Molecular Simulation},
 journal = {J. Chem. Theory Comput.},
 volume = {4},
 number = {3},
 pages = {435-447},
 year = {2008},
 doi = {10.1021/ct700301q},
 note = {PMID: 26620784},
 URL = {https://doi.org/10.1021/ct700301q},
 eprint = {http://dx.doi.org/10.1021/ct700301q},
 abstract = {Molecular simulation is an extremely useful, but computationally very expensive tool for studies of chemical and biomolecular systems. Here, we present a new implementation of our molecular simulation toolkit GROMACS which now both achieves extremely high performance on single processors from algorithmic optimizations and hand-coded routines and simultaneously scales very well on parallel machines. The code encompasses a minimal-communication domain decomposition algorithm, full dynamic load balancing, a state-of-the-art parallel constraint solver, and efficient virtual site algorithms that allow removal of hydrogen atom degrees of freedom to enable integration time steps up to 5 fs for atomistic simulations also in parallel. To improve the scaling properties of the common particle mesh Ewald electrostatics algorithms, we have in addition used a Multiple-Program, Multiple-Data approach, with separate node domains responsible for direct and reciprocal space interactions. Not only does this combination of algorithms enable extremely long simulations of large systems but also it provides that simulation performance on quite modest numbers of standard cluster nodes.},
 source = {Crossref},
 publisher = {American Chemical Society (ACS)},
 issn = {1549-9618, 1549-9626},
 month = mar,
}
```
Perhaps be more specific?

**Comment by koroki** [comment]
Yes, I forgot to say one step that I do that seams more important.
I have my own bib file, with many references. I downloaded the bibtext from the website, I copy the text to my own bib file. When I did this steps, the betterbib fails with the error that I pasted before.
However, the betterbib works properly with the bib file downloaded form the website. 

I checked the files and the two are UTF-8. Checking with `file -bi` obtain the same result: text/plain; charset=utf-8

The point is, when I change the ":" from the original bib file for a "normal" ones, betterbib works.

**Comment by nschloe** [comment]
> The point is, when I change the ":" from the original bib file for a "normal" ones, betterbib works.

I understand. I just need to be able to _reproduce_ it so I can do anything about it.

> I have my own bib file, with many references. I downloaded the bibtext from the website, I copy the text to my own bib file. When I did this steps, the betterbib fails with the error that I pasted before.
However, the betterbib works properly with the bib file downloaded form the website.

I still don't quite get what you're saying. You download something from a website and include it into your bibfile and then betterbib fails, but if you download it it from the website it works?

What do I have to do so I can see the error here on my machine?

**Comment by koroki** [comment]
> I still don't quite get what you're saying. You download something from a website and include it into your bibfile and then betterbib fails, but if you download it it from the website it works?

Exactly.

I'm not sure how to reproduce in your machine since I cannot reproduce allways in my machine, sorry. I'll explore more the error and I'll come here again

**Comment by yunesj** [comment]
I avoided unicode errors by running betterbib with python3.
